#include "../../kompiler.h"

struct state stMachine[MAXSTATES][TOTALMAPS] = {
{ /* State row 0 - Default state */
	/* JUNK */ {ERRST, &errFunc, 0},
	/* WHITESPACE */ {DISCARDST, &discard, 0},
	/* NUMBERS */ {NUMBERST, &accumulate, 0},
	/* CHARS */ {IDST, &accumulate, 0},
	/* NEWLINE */ {DISCARDST, &discard, 0},
	/* ' */ {CHARST, &charSTFunc, 0},
	/* " */ {STRINGST, &strSTFunc, 0},
	/* PLUS */ {PLUSST, &tokFunc, 0},//+ ++ +=
	/* MINUS */ {MINUSST, &tokFunc, 0},//- -- -= ->
	/* STAR */ {STARST, &tokFunc, 0},//* *=
	/* SLASH */ {SLASHST, &slashFunc, 0}, // / /=
	/* MOD */ {MODST, &tokFunc, 0},//% %=
	/* ! */ {NOTST, &tokFunc, 0},//! !=
	/* & */ {ANDST, &tokFunc, 0},//& && &=
	/* | */ {ORST, &tokFunc, 0},//| || |=
	/* < */ {LTST, &tokFunc, 0},//< << <=
	/* > */ {GTST, &tokFunc, 0},//> >> >=
	/* = */ {EQST, &tokFunc, 0},//= == 
	/* ~ */ {TOKST, &returnTok, TILDETOK},
	/* ( */ {TOKST, &returnTok, LPARANTOK},
	/* ) */ {TOKST, &returnTok, RPARANTOK},
	/* [ */ {TOKST, &returnTok, LBRACTOK},
	/* ] */ {TOKST, &returnTok, RBRACTOK},
	/* { */ {TOKST, &returnTok, LCURLYTOK},
	/* } */ {TOKST, &returnTok, RCURLYTOK},
	/* , */ {TOKST, &returnTok, COMMATOK},
	/* . */ {FLOATST, &accumulate, 0},
	/* ? */ {TOKST, &returnTok, QUESTIONTOK},
	/* : */ {ERRST, &errFunc, COLONTOK},
	/* ; */ {TOKST, &returnTok, SEMICOLTOK},
	/* ^ */ {CARETST, &tokFunc, 0},//^ ^=
	/* _ */ {IDST, &accumulate, 0},
	/* \ */ {ERRST, &errFunc, 0},
	/* # */ {TOKST, &returnTok, POUNDTOK}
}

,{ /* State row 1 - NUMBERST */
	/* JUNK */ {ERRST, &errFunc, 0},
	/* WHITESPACE */ {INTACCST, &returnTok, NUMBERTOK},
	/* NUMBERS */ {NUMBERST, &accumulate, 0},
	/* CHARS */ {ERRST, &errFunc, 0},
	/* NEWLINE */ {INTACCST, &returnTok, NUMBERTOK},
	/* ' */ {ERRST, &errFunc, 0},
	/* " */ {ERRST, &errFunc, 0},
	/* PLUS */ {INTACCST, &returnTok, NUMBERTOK},
	/* MINUS */ {INTACCST, &returnTok, NUMBERTOK},
	/* STAR */ {INTACCST, &returnTok, NUMBERTOK},
	/* SLASH */ {INTACCST, &returnTok, NUMBERTOK},
	/* MOD */ {INTACCST, &returnTok, NUMBERTOK},
	/* ! */ {INTACCST, &returnTok, NUMBERTOK},
	/* & */ {INTACCST, &returnTok, NUMBERTOK},
	/* | */ {INTACCST, &returnTok, NUMBERTOK},
	/* < */ {INTACCST, &returnTok, NUMBERTOK},
	/* > */ {INTACCST, &returnTok, NUMBERTOK},
	/* = */ {INTACCST, &returnTok, NUMBERTOK},
	/* ~ */ {ERRST, &errFunc, 0},
	/* ( */ {ERRST, &errFunc, 0},
	/* ) */ {INTACCST, &returnTok, NUMBERTOK},
	/* [ */ {ERRST, &errFunc, 0},
	/* ] */ {INTACCST, &returnTok, NUMBERTOK},
	/* { */ {ERRST, &errFunc, 0},
	/* } */ {INTACCST, &returnTok, NUMBERTOK},
	/* , */ {INTACCST, &returnTok, NUMBERTOK},
	/* . */ {FLOATST, &accumulate, 0},
	/* ? */ {INTACCST, &returnTok, NUMBERTOK},
	/* : */ {ERRST, &errFunc, 0},
	/* ; */ {INTACCST, &returnTok, NUMBERTOK},
	/* ^ */ {INTACCST, &returnTok, NUMBERTOK},
	/* _ */ {ERRST, &errFunc, 0},
	/* \ */ {ERRST, &errFunc, 0},
	/* # */ {ERRST, &errFunc, 0}
}

,{ /* State row 2 - FLOATST */
	/* JUNK */ {ERRST, &errFunc, 0},
	/* WHITESPACE */ {FLOACCST, &returnTok, FLOATTOK},
	/* NUMBERS */ {FLOATST, &accumulate, 0},
	/* CHARS */ {ERRST, &errFunc, 0},
	/* NEWLINE */ {FLOACCST, &returnTok, FLOATTOK},
	/* ' */ {ERRST, &errFunc, 0},
	/* " */ {ERRST, &errFunc, 0},
	/* PLUS */ {FLOACCST, &returnTok, FLOATTOK},
	/* MINUS */ {FLOACCST, &returnTok, FLOATTOK},
	/* STAR */ {FLOACCST, &returnTok, FLOATTOK},
	/* SLASH */ {FLOACCST, &returnTok, FLOATTOK},
	/* MOD */ {FLOACCST, &returnTok, FLOATTOK},
	/* ! */ {FLOACCST, &returnTok, FLOATTOK},
	/* & */ {FLOACCST, &returnTok, FLOATTOK},
	/* | */ {FLOACCST, &returnTok, FLOATTOK},
	/* < */ {FLOACCST, &returnTok, FLOATTOK},
	/* > */ {FLOACCST, &returnTok, FLOATTOK},
	/* = */ {FLOACCST, &returnTok, FLOATTOK},
	/* ~ */ {ERRST, &errFunc, 0},
	/* ( */ {ERRST, &errFunc, 0},
	/* ) */ {FLOACCST, &returnTok, FLOATTOK},
	/* [ */ {ERRST, &errFunc, 0},
	/* ] */ {FLOACCST, &returnTok, FLOATTOK},
	/* { */ {ERRST, &errFunc, 0},
	/* } */ {FLOACCST, &returnTok, FLOATTOK},
	/* , */ {FLOACCST, &returnTok, FLOATTOK},
	/* . */ {ERRST, &errFunc, 0},
	/* ? */ {FLOACCST, &returnTok, FLOATTOK},
	/* : */ {ERRST, &errFunc, 0},
	/* ; */ {FLOACCST, &returnTok, FLOATTOK},
	/* ^ */ {FLOACCST, &returnTok, FLOATTOK},
	/* _ */ {ERRST, &errFunc, 0},
	/* \ */ {ERRST, &errFunc, 0},
	/* # */ {ERRST, &errFunc, 0}
}

,{ /* State row 3 - IDST (ID state) */
	/* JUNK */ {ERRST, &errFunc, 0},
	/* WHITESPACE */ {IDACCST, &returnTok, IDTOKEN},
	/* NUMBERS */ {IDST, &accumulate, 0},
	/* CHARS */ {IDST, &accumulate, 0},
	/* NEWLINE */ {IDACCST, &returnTok, IDTOKEN},
	/* ' */ {ERRST, &errFunc, 0},
	/* " */ {ERRST, &errFunc, 0},
	/* PLUS */ {IDACCST, &returnTok, IDTOKEN},
	/* MINUS */ {IDACCST, &returnTok, IDTOKEN},
	/* STAR */ {IDACCST, &returnTok, IDTOKEN},
	/* SLASH */ {IDACCST, &returnTok, IDTOKEN},
	/* MOD */ {IDACCST, &returnTok, IDTOKEN},
	/* ! */ {IDACCST, &returnTok, IDTOKEN},
	/* & */ {IDACCST, &returnTok, IDTOKEN},
	/* | */ {IDACCST, &returnTok, IDTOKEN},
	/* < */ {IDACCST, &returnTok, IDTOKEN},
	/* > */ {IDACCST, &returnTok, IDTOKEN},
	/* = */ {IDACCST, &returnTok, IDTOKEN},
	/* ~ */ {IDACCST, &returnTok, IDTOKEN},
	/* ( */ {IDACCST, &returnTok, IDTOKEN},
	/* ) */ {IDACCST, &returnTok, IDTOKEN},
	/* [ */ {IDACCST, &returnTok, IDTOKEN},
	/* ] */ {IDACCST, &returnTok, IDTOKEN},
	/* { */ {IDACCST, &returnTok, IDTOKEN},
	/* } */ {IDACCST, &returnTok, IDTOKEN},
	/* , */ {IDACCST, &returnTok, IDTOKEN},
	/* . */ {IDST, &accumulate, 0}, //for structs in the future
	/* ? */ {IDACCST, &returnTok, IDTOKEN},
	/* : */ {ERRST, &errFunc, 0},
	/* ; */ {IDACCST, &returnTok, IDTOKEN},
	/* ^ */ {IDACCST, &returnTok, IDTOKEN},
	/* _ */ {IDST, &accumulate, 0},
	/* \ */ {ERRST, &errFunc, 0},
	/* # */ {ERRST, &errFunc, 0}
}

,{ /* State row 4 - CHARST */
	/* JUNK */ {CHARST2, &storeAndGrab, 0},
	/* WHITESPACE */ {CHARST2, &storeAndGrab, 0},
	/* NUMBERS */ {CHARST2, &storeAndGrab, 0},
	/* CHARS */ {CHARST2, &storeAndGrab, 0},
	/* NEWLINE */ {CHARST2, &storeAndGrab, 0},
	/* ' */ {CHARACCST, &returnTok, CHARTOKEN},
	/* " */ {CHARST2, &storeAndGrab, 0},
	/* PLUS */ {CHARST2, &storeAndGrab, 0},
	/* MINUS */ {CHARST2, &storeAndGrab, 0},
	/* STAR */ {CHARST2, &storeAndGrab, 0},
	/* SLASH */ {CHARST2, &storeAndGrab, 0},
	/* MOD */ {CHARST2, &storeAndGrab, 0},
	/* ! */ {CHARST2, &storeAndGrab, 0},
	/* & */ {CHARST2, &storeAndGrab, 0},
	/* | */ {CHARST2, &storeAndGrab, 0},
	/* < */ {CHARST2, &storeAndGrab, 0},
	/* > */ {CHARST2, &storeAndGrab, 0},
	/* = */ {CHARST2, &storeAndGrab, 0},
	/* ~ */ {CHARST2, &storeAndGrab, 0},
	/* ( */ {CHARST2, &storeAndGrab, 0},
	/* ) */ {CHARST2, &storeAndGrab, 0},
	/* [ */ {CHARST2, &storeAndGrab, 0},
	/* ] */ {CHARST2, &storeAndGrab, 0},
	/* { */ {CHARST2, &storeAndGrab, 0},
	/* } */ {CHARST2, &storeAndGrab, 0},
	/* , */ {CHARST2, &storeAndGrab, 0},
	/* . */ {CHARST2, &storeAndGrab, 0},
	/* ? */ {CHARST2, &storeAndGrab, 0},
	/* : */ {CHARST2, &storeAndGrab, 0},
	/* ; */ {CHARST2, &storeAndGrab, 0},
	/* ^ */ {CHARST2, &storeAndGrab, 0},
	/* _ */ {CHARST2, &storeAndGrab, 0},
	/* \ */ {CHARESCST, &grabNextCh, 0},
	/* # */ {ERRST, &errFunc, 0}
}

,{ /* State row 5 - CHARST2 (Check for ending ') */
	/* JUNK */ {ERRST, &errFunc, 0},
	/* WHITESPACE */ {ERRST, &errFunc, 0},
	/* NUMBERS */ {ERRST, &errFunc, 0},
	/* CHARS */ {ERRST, &errFunc, 0},
	/* NEWLINE */ {ERRST, &errFunc, 0},
	/* ' */ {CHARACCST, &returnTok, CHARTOKEN},
	/* " */ {ERRST, &errFunc, 0},
	/* PLUS */ {ERRST, &errFunc, 0},
	/* MINUS */ {ERRST, &errFunc, 0},
	/* STAR */ {ERRST, &errFunc, 0},
	/* SLASH */ {ERRST, &errFunc, 0},
	/* MOD */ {ERRST, &errFunc, 0},
	/* ! */ {ERRST, &errFunc, 0},
	/* & */ {ERRST, &errFunc, 0},
	/* | */ {ERRST, &errFunc, 0},
	/* < */ {ERRST, &errFunc, 0},
	/* > */ {ERRST, &errFunc, 0},
	/* = */ {ERRST, &errFunc, 0},
	/* ~ */ {ERRST, &errFunc, 0},
	/* ( */ {ERRST, &errFunc, 0},
	/* ) */ {ERRST, &errFunc, 0},
	/* [ */ {ERRST, &errFunc, 0},
	/* ] */ {ERRST, &errFunc, 0},
	/* { */ {ERRST, &errFunc, 0},
	/* } */ {ERRST, &errFunc, 0},
	/* , */ {ERRST, &errFunc, 0},
	/* . */ {ERRST, &errFunc, 0},
	/* ? */ {ERRST, &errFunc, 0},
	/* : */ {ERRST, &errFunc, 0},
	/* ; */ {ERRST, &errFunc, 0},
	/* ^ */ {ERRST, &errFunc, 0},
	/* _ */ {ERRST, &errFunc, 0},
	/* \ */ {ERRST, &errFunc, 0},
	/* # */ {ERRST, &errFunc, 0}
}

,{ /* State row 6 - CHARESCST (Escape \ and ') */
	/* JUNK */ {ERRST, &errFunc, 0},
	/* WHITESPACE */ {ERRST, &errFunc, 0},
	/* NUMBERS */ {ERRST, &errFunc, 0},
	/* CHARS */ {CHARST2, &escChar, 0},
	/* NEWLINE */ {ERRST, &errFunc, 0},
	/* ' */ {CHARST2, &storeAndGrab, 0},
	/* " */ {ERRST, &errFunc, 0},
	/* PLUS */ {ERRST, &errFunc, 0},
	/* MINUS */ {ERRST, &errFunc, 0},
	/* STAR */ {ERRST, &errFunc, 0},
	/* SLASH */ {ERRST, &errFunc, 0},
	/* MOD */ {ERRST, &errFunc, 0},
	/* ! */ {ERRST, &errFunc, 0},
	/* & */ {ERRST, &errFunc, 0},
	/* | */ {ERRST, &errFunc, 0},
	/* < */ {ERRST, &errFunc, 0},
	/* > */ {ERRST, &errFunc, 0},
	/* = */ {ERRST, &errFunc, 0},
	/* ~ */ {ERRST, &errFunc, 0},
	/* ( */ {ERRST, &errFunc, 0},
	/* ) */ {ERRST, &errFunc, 0},
	/* [ */ {ERRST, &errFunc, 0},
	/* ] */ {ERRST, &errFunc, 0},
	/* { */ {ERRST, &errFunc, 0},
	/* } */ {ERRST, &errFunc, 0},
	/* , */ {ERRST, &errFunc, 0},
	/* . */ {ERRST, &errFunc, 0},
	/* ? */ {ERRST, &errFunc, 0},
	/* : */ {ERRST, &errFunc, 0},
	/* ; */ {ERRST, &errFunc, 0},
	/* ^ */ {ERRST, &errFunc, 0},
	/* _ */ {ERRST, &errFunc, 0},
	/* \ */ {CHARST2, &storeAndGrab, 0},
	/* # */ {ERRST, &errFunc, 0}
}

,{ /* State row 7 - STRINGST (First " found) */
	/* JUNK */ {STRINGST, &accumulate, 0},
	/* WHITESPACE */ {STRINGST, &accumulate, 0},
	/* NUMBERS */ {STRINGST, &accumulate, 0},
	/* CHARS */ {STRINGST, &accumulate, 0},
	/* NEWLINE */ {STRINGST, &accumulate, 0},
	/* ' */ {STRINGST, &accumulate, 0},
	/* " */ {STRACCST, &returnTok, STRTOKEN},
	/* PLUS */ {STRINGST, &accumulate, 0},
	/* MINUS */ {STRINGST, &accumulate, 0},
	/* STAR */ {STRINGST, &accumulate, 0},
	/* SLASH */ {STRINGST, &accumulate, 0},
	/* MOD */ {STRINGST, &accumulate, 0},
	/* ! */ {STRINGST, &accumulate, 0},
	/* & */ {STRINGST, &accumulate, 0},
	/* | */ {STRINGST, &accumulate, 0},
	/* < */ {STRINGST, &accumulate, 0},
	/* > */ {STRINGST, &accumulate, 0},
	/* = */ {STRINGST, &accumulate, 0},
	/* ~ */ {STRINGST, &accumulate, 0},
	/* ( */ {STRINGST, &accumulate, 0},
	/* ) */ {STRINGST, &accumulate, 0},
	/* [ */ {STRINGST, &accumulate, 0},
	/* ] */ {STRINGST, &accumulate, 0},
	/* { */ {STRINGST, &accumulate, 0},
	/* } */ {STRINGST, &accumulate, 0},
	/* , */ {STRINGST, &accumulate, 0},
	/* . */ {STRINGST, &accumulate, 0},
	/* ? */ {STRINGST, &accumulate, 0},
	/* : */ {STRINGST, &accumulate, 0},
	/* ; */ {STRINGST, &accumulate, 0},
	/* ^ */ {STRINGST, &accumulate, 0},
	/* _ */ {STRINGST, &accumulate, 0},
	/* \ */ {STRESCST, &grabNextCh, 0},
	/* # */ {STRINGST, &accumulate, 0}
}

,{ /* State row 8 - STRESCST (Escape \ and ") */
	/* JUNK */ {ERRST, &errFunc, 0},
	/* WHITESPACE */ {ERRST, &errFunc, 0},
	/* NUMBERS */ {ERRST, &errFunc, 0},
	/* CHARS */ {STRINGST, &escChar, 0}, //change this 
	/* NEWLINE */ {ERRST, &errFunc, 0},
	/* ' */ {ERRST, &errFunc, 0},
	/* " */ {STRINGST, &accumulate, 0},
	/* PLUS */ {ERRST, &errFunc, 0},
	/* MINUS */ {ERRST, &errFunc, 0},
	/* STAR */ {ERRST, &errFunc, 0},
	/* SLASH */ {ERRST, &errFunc, 0},
	/* MOD */ {ERRST, &errFunc, 0},
	/* ! */ {ERRST, &errFunc, 0},
	/* & */ {ERRST, &errFunc, 0},
	/* | */ {ERRST, &errFunc, 0},
	/* < */ {ERRST, &errFunc, 0},
	/* > */ {ERRST, &errFunc, 0},
	/* = */ {ERRST, &errFunc, 0},
	/* ~ */ {ERRST, &errFunc, 0},
	/* ( */ {ERRST, &errFunc, 0},
	/* ) */ {ERRST, &errFunc, 0},
	/* [ */ {ERRST, &errFunc, 0},
	/* ] */ {ERRST, &errFunc, 0},
	/* { */ {ERRST, &errFunc, 0},
	/* } */ {ERRST, &errFunc, 0},
	/* , */ {ERRST, &errFunc, 0},
	/* . */ {ERRST, &errFunc, 0},
	/* ? */ {ERRST, &errFunc, 0},
	/* : */ {ERRST, &errFunc, 0},
	/* ; */ {ERRST, &errFunc, 0},
	/* ^ */ {ERRST, &errFunc, 0},
	/* _ */ {ERRST, &errFunc, 0},
	/* \ */ {STRINGST, &accumulate, 0},
	/* # */ {ERRST, &errFunc, 0}
}

,{ /* State row 9 - SLASHST (First slash) */
	/* JUNK */ {ERRST, &errFunc, 0},
	/* WHITESPACE */ {TOKST, &returnTok, DIVTOK},
	/* NUMBERS */ {TOKST, &returnTok, DIVTOK},
	/* CHARS */ {TOKST, &returnTok, DIVTOK},
	/* NEWLINE */ {ERRST, &errFunc, 0},
	/* ' */ {ERRST, &errFunc, 0},
	/* " */ {ERRST, &errFunc, 0},
	/* PLUS */ {ERRST, &errFunc, 0},
	/* MINUS */ {ERRST, &errFunc, 0},
	/* STAR */ {COMMENTST, &discard, 0},
	/* SLASH */ {COMMSLST, &discard, 0},
	/* MOD */ {ERRST, &errFunc, 0},
	/* ! */ {ERRST, &errFunc, 0},
	/* & */ {ERRST, &errFunc, 0},
	/* | */ {ERRST, &errFunc, 0},
	/* < */ {ERRST, &errFunc, 0},
	/* > */ {ERRST, &errFunc, 0},
	/* = */ {TOKST, &returnTok, DIVEQ},
	/* ~ */ {ERRST, &errFunc, 0},
	/* ( */ {ERRST, &errFunc, 0},
	/* ) */ {ERRST, &errFunc, 0},
	/* [ */ {ERRST, &errFunc, 0},
	/* ] */ {ERRST, &errFunc, 0},
	/* { */ {ERRST, &errFunc, 0},
	/* } */ {ERRST, &errFunc, 0},
	/* , */ {ERRST, &errFunc, 0},
	/* . */ {ERRST, &errFunc, 0},
	/* ? */ {ERRST, &errFunc, 0},
	/* : */ {ERRST, &errFunc, 0},
	/* ; */ {ERRST, &errFunc, 0},
	/* ^ */ {ERRST, &errFunc, 0},
	/* _ */ {ERRST, &errFunc, 0},
	/* \ */ {ERRST, &errFunc, 0},
	/* # */ {ERRST, &errFunc, 0}
}

,{ /* State row 10 - COMMENTST (Throw it all away!) */
	/* JUNK */ {COMMENTST, &discard, 0},
	/* WHITESPACE */ {COMMENTST, &discard, 0},
	/* NUMBERS */ {COMMENTST, &discard, 0},
	/* CHARS */ {COMMENTST, &discard, 0},
	/* NEWLINE */ {COMMENTST, &discard, 0},
	/* ' */ {COMMENTST, &discard, 0},
	/* " */ {COMMENTST, &discard, 0},
	/* PLUS */ {COMMENTST, &discard, 0},
	/* MINUS */ {COMMENTST, &discard, 0},
	/* STAR */ {LEAVECOMMST, &discard, 0},
	/* SLASH */ {COMMENTST, &discard, 0},
	/* MOD */ {COMMENTST, &discard, 0},
	/* ! */ {COMMENTST, &discard, 0},
	/* & */ {COMMENTST, &discard, 0},
	/* | */ {COMMENTST, &discard, 0},
	/* < */ {COMMENTST, &discard, 0},
	/* > */ {COMMENTST, &discard, 0},
	/* = */ {COMMENTST, &discard, 0},
	/* ~ */ {COMMENTST, &discard, 0},
	/* ( */ {COMMENTST, &discard, 0},
	/* ) */ {COMMENTST, &discard, 0},
	/* [ */ {COMMENTST, &discard, 0},
	/* ] */ {COMMENTST, &discard, 0},
	/* { */ {COMMENTST, &discard, 0},
	/* } */ {COMMENTST, &discard, 0},
	/* , */ {COMMENTST, &discard, 0},
	/* . */ {COMMENTST, &discard, 0},
	/* ? */ {COMMENTST, &discard, 0},
	/* : */ {COMMENTST, &discard, 0},
	/* ; */ {COMMENTST, &discard, 0},
	/* ^ */ {COMMENTST, &discard, 0},
	/* _ */ {COMMENTST, &discard, 0},
	/* \ */ {COMMENTST, &discard, 0},
	/* # */ {COMMENTST, &discard, 0}
}

,{ /* State row 11 - LEAVECOMMST (Did we find the end of comment?) */
	/* JUNK */ {COMMENTST, &discard, 0},
	/* WHITESPACE */ {COMMENTST, &discard, 0},
	/* NUMBERS */ {COMMENTST, &discard, 0},
	/* CHARS */ {COMMENTST, &discard, 0},
	/* NEWLINE */ {COMMENTST, &discard, 0},
	/* ' */ {COMMENTST, &discard, 0},
	/* " */ {COMMENTST, &discard, 0},
	/* PLUS */ {COMMENTST, &discard, 0},
	/* MINUS */ {COMMENTST, &discard, 0},
	/* STAR */ {LEAVECOMMST, &discard, 0},
	/* SLASH */ {DEFAULTST, &backToDefault, 0},
	/* MOD */ {COMMENTST, &discard, 0},
	/* ! */ {COMMENTST, &discard, 0},
	/* & */ {COMMENTST, &discard, 0},
	/* | */ {COMMENTST, &discard, 0},
	/* < */ {COMMENTST, &discard, 0},
	/* > */ {COMMENTST, &discard, 0},
	/* = */ {COMMENTST, &discard, 0},
	/* ~ */ {COMMENTST, &discard, 0},
	/* ( */ {COMMENTST, &discard, 0},
	/* ) */ {COMMENTST, &discard, 0},
	/* [ */ {COMMENTST, &discard, 0},
	/* ] */ {COMMENTST, &discard, 0},
	/* { */ {COMMENTST, &discard, 0},
	/* } */ {COMMENTST, &discard, 0},
	/* , */ {COMMENTST, &discard, 0},
	/* . */ {COMMENTST, &discard, 0},
	/* ? */ {COMMENTST, &discard, 0},
	/* : */ {COMMENTST, &discard, 0},
	/* ; */ {COMMENTST, &discard, 0},
	/* ^ */ {COMMENTST, &discard, 0},
	/* _ */ {COMMENTST, &discard, 0},
	/* \ */ {COMMENTST, &discard, 0},
	/* # */ {COMMENTST, &discard, 0}
}

,{ /* State row 12 - COMMSLST (Comment single line //) */
	/* JUNK */ {COMMSLST, &discard, 0},
	/* WHITESPACE */ {COMMSLST, &discard, 0},
	/* NUMBERS */ {COMMSLST, &discard, 0},
	/* CHARS */ {COMMSLST, &discard, 0},
	/* NEWLINE */ {DEFAULTST, &backToDefault, 0},
	/* ' */ {COMMSLST, &discard, 0},
	/* " */ {COMMSLST, &discard, 0},
	/* PLUS */ {COMMSLST, &discard, 0},
	/* MINUS */ {COMMSLST, &discard, 0},
	/* STAR */ {COMMSLST, &discard, 0},
	/* SLASH */ {COMMSLST, &discard, 0},
	/* MOD */ {COMMSLST, &discard, 0},
	/* ! */ {COMMSLST, &discard, 0},
	/* & */ {COMMSLST, &discard, 0},
	/* | */ {COMMSLST, &discard, 0},
	/* < */ {COMMSLST, &discard, 0},
	/* > */ {COMMSLST, &discard, 0},
	/* = */ {COMMSLST, &discard, 0},
	/* ~ */ {COMMSLST, &discard, 0},
	/* ( */ {COMMSLST, &discard, 0},
	/* ) */ {COMMSLST, &discard, 0},
	/* [ */ {COMMSLST, &discard, 0},
	/* ] */ {COMMSLST, &discard, 0},
	/* { */ {COMMSLST, &discard, 0},
	/* } */ {COMMSLST, &discard, 0},
	/* , */ {COMMSLST, &discard, 0},
	/* . */ {COMMSLST, &discard, 0},
	/* ? */ {COMMSLST, &discard, 0},
	/* : */ {COMMSLST, &discard, 0},
	/* ; */ {COMMSLST, &discard, 0},
	/* ^ */ {COMMSLST, &discard, 0},
	/* _ */ {COMMSLST, &discard, 0},
	/* \ */ {COMMSLST, &discard, 0},
	/* # */ {COMMSLST, &discard, 0}
}

,{ /* State row 13 - PLUSST (First + found) */
	/* JUNK */ {ERRST, &errFunc, 0},
	/* WHITESPACE */ {TOKST, &returnTok, PLUSTOK},
	/* NUMBERS */ {TOKST, &returnTok, PLUSTOK},
	/* CHARS */ {TOKST, &returnTok, PLUSTOK},
	/* NEWLINE */ {TOKST, &returnTok, PLUSTOK},
	/* ' */ {TOKST, &returnTok, PLUSTOK},
	/* " */ {TOKST, &returnTok, PLUSTOK},
	/* PLUS */ {TOKST, &returnTok, PLUSPLUS},
	/* MINUS */ {ERRST, &errFunc, 0},
	/* STAR */ {ERRST, &errFunc, 0},
	/* SLASH */ {ERRST, &errFunc, 0},
	/* MOD */ {ERRST, &errFunc, 0},
	/* ! */ {ERRST, &errFunc, 0},
	/* & */ {ERRST, &errFunc, 0},
	/* | */ {ERRST, &errFunc, 0},
	/* < */ {ERRST, &errFunc, 0},
	/* > */ {ERRST, &errFunc, 0},
	/* = */ {TOKST, &returnTok, PLUSEQ},
	/* ~ */ {ERRST, &errFunc, 0},
	/* ( */ {TOKST, &returnTok, PLUSTOK},
	/* ) */ {ERRST, &errFunc, 0},
	/* [ */ {ERRST, &errFunc, 0},
	/* ] */ {ERRST, &errFunc, 0},
	/* { */ {ERRST, &errFunc, 0},
	/* } */ {ERRST, &errFunc, 0},
	/* , */ {ERRST, &errFunc, 0},
	/* . */ {ERRST, &errFunc, 0},
	/* ? */ {ERRST, &errFunc, 0},
	/* : */ {ERRST, &errFunc, 0},
	/* ; */ {ERRST, &errFunc, 0},
	/* ^ */ {ERRST, &errFunc, 0},
	/* _ */ {TOKST, &returnTok, PLUSTOK},
	/* \ */ {ERRST, &errFunc, 0},
	/* # */ {ERRST, &errFunc, 0}
}

,{ /* State row 14 - MINUSST (First - found)*/
	/* JUNK */ {ERRST, &errFunc, 0},
	/* WHITESPACE */ {TOKST, &returnTok, MINUSTOK},
	/* NUMBERS */ {TOKST, &returnTok, MINUSTOK},
	/* CHARS */ {TOKST, &returnTok, MINUSTOK},
	/* NEWLINE */ {TOKST, &returnTok, MINUSTOK},
	/* ' */ {TOKST, &returnTok, MINUSTOK},
	/* " */ {TOKST, &returnTok, MINUSTOK},
	/* PLUS */ {ERRST, &errFunc, 0},
	/* MINUS */ {TOKST, &returnTok, MINUSMINUS},
	/* STAR */ {ERRST, &errFunc, 0},
	/* SLASH */ {ERRST, &errFunc, 0},
	/* MOD */ {ERRST, &errFunc, 0},
	/* ! */ {ERRST, &errFunc, 0},
	/* & */ {ERRST, &errFunc, 0},
	/* | */ {ERRST, &errFunc, 0},
	/* < */ {ERRST, &errFunc, 0},
	/* > */ {TOKST, &storeAndGrab, ARROW},
	/* = */ {TOKST, &returnTok, MINUSEQ},
	/* ~ */ {ERRST, &errFunc, 0},
	/* ( */ {TOKST, &returnTok, MINUSTOK},
	/* ) */ {ERRST, &errFunc, 0},
	/* [ */ {ERRST, &errFunc, 0},
	/* ] */ {ERRST, &errFunc, 0},
	/* { */ {ERRST, &errFunc, 0},
	/* } */ {ERRST, &errFunc, 0},
	/* , */ {ERRST, &errFunc, 0},
	/* . */ {ERRST, &errFunc, 0},
	/* ? */ {ERRST, &errFunc, 0},
	/* : */ {ERRST, &errFunc, 0},
	/* ; */ {ERRST, &errFunc, 0},
	/* ^ */ {ERRST, &errFunc, 0},
	/* _ */ {TOKST, &returnTok, MINUSTOK},
	/* \ */ {ERRST, &errFunc, 0},
	/* # */ {ERRST, &errFunc, 0}
}

,{ /* State row 15 - STARST (First * found)*/
	/* JUNK */ {ERRST, &errFunc, 0},
	/* WHITESPACE */ {TOKST, &returnTok, STARTOK},
	/* NUMBERS */ {TOKST, &returnTok, STARTOK},
	/* CHARS */ {TOKST, &returnTok, STARTOK},
	/* NEWLINE */ {TOKST, &returnTok, STARTOK},
	/* ' */ {TOKST, &returnTok, STARTOK},
	/* " */ {TOKST, &returnTok, STARTOK},
	/* PLUS */ {ERRST, &errFunc, 0},
	/* MINUS */ {ERRST, &errFunc, 0},
	/* STAR */ {TOKST, &returnTok, STARSTAR},
	/* SLASH */ {ERRST, &errFunc, 0},
	/* MOD */ {ERRST, &errFunc, 0},
	/* ! */ {ERRST, &errFunc, 0},
	/* & */ {ERRST, &errFunc, 0},
	/* | */ {ERRST, &errFunc, 0},
	/* < */ {ERRST, &errFunc, 0},
	/* > */ {ERRST, &errFunc, 0},
	/* = */ {TOKST, &returnTok, STAREQ},
	/* ~ */ {ERRST, &errFunc, 0},
	/* ( */ {TOKST, &returnTok, STARTOK},
	/* ) */ {ERRST, &errFunc, 0},
	/* [ */ {ERRST, &errFunc, 0},
	/* ] */ {ERRST, &errFunc, 0},
	/* { */ {ERRST, &errFunc, 0},
	/* } */ {ERRST, &errFunc, 0},
	/* , */ {ERRST, &errFunc, 0},
	/* . */ {ERRST, &errFunc, 0},
	/* ? */ {ERRST, &errFunc, 0},
	/* : */ {ERRST, &errFunc, 0},
	/* ; */ {ERRST, &errFunc, 0},
	/* ^ */ {ERRST, &errFunc, 0},
	/* _ */ {TOKST, &returnTok, STARTOK},
	/* \ */ {ERRST, &errFunc, 0},
	/* # */ {ERRST, &errFunc, 0}
}

,{ /* State row 16 - MODST (First % found)*/
	/* JUNK */ {ERRST, &errFunc, 0},
	/* WHITESPACE */ {TOKST, &returnTok, MODTOK},
	/* NUMBERS */ {TOKST, &returnTok, MODTOK},
	/* CHARS */ {TOKST, &returnTok, MODTOK},
	/* NEWLINE */ {TOKST, &returnTok, MODTOK},
	/* ' */ {TOKST, &returnTok, MODTOK},
	/* " */ {TOKST, &returnTok, MODTOK},
	/* PLUS */ {ERRST, &errFunc, 0},
	/* MINUS */ {ERRST, &errFunc, 0},
	/* STAR */ {ERRST, &errFunc, 0},
	/* SLASH */ {ERRST, &errFunc, 0},
	/* MOD */ {ERRST, &errFunc, 0},
	/* ! */ {ERRST, &errFunc, 0},
	/* & */ {ERRST, &errFunc, 0},
	/* | */ {ERRST, &errFunc, 0},
	/* < */ {ERRST, &errFunc, 0},
	/* > */ {ERRST, &errFunc, 0},
	/* = */ {TOKST, &returnTok, MODEQ},
	/* ~ */ {ERRST, &errFunc, 0},
	/* ( */ {TOKST, &returnTok, MODTOK},
	/* ) */ {ERRST, &errFunc, 0},
	/* [ */ {ERRST, &errFunc, 0},
	/* ] */ {ERRST, &errFunc, 0},
	/* { */ {ERRST, &errFunc, 0},
	/* } */ {ERRST, &errFunc, 0},
	/* , */ {ERRST, &errFunc, 0},
	/* . */ {ERRST, &errFunc, 0},
	/* ? */ {ERRST, &errFunc, 0},
	/* : */ {ERRST, &errFunc, 0},
	/* ; */ {ERRST, &errFunc, 0},
	/* ^ */ {ERRST, &errFunc, 0},
	/* _ */ {TOKST, &returnTok, MODTOK},
	/* \ */ {ERRST, &errFunc, 0},
	/* # */ {ERRST, &errFunc, 0}
}

,{ /* State row 17 - NOTST (First ! found)*/
	/* JUNK */ {ERRST, &errFunc, 0},
	/* WHITESPACE */ {TOKST, &returnTok, NOTTOK},
	/* NUMBERS */ {ERRST, &errFunc, 0},
	/* CHARS */ {TOKST, &returnTok, NOTTOK},
	/* NEWLINE */ {TOKST, &returnTok, NOTTOK},
	/* ' */ {ERRST, &errFunc, 0},
	/* " */ {ERRST, &errFunc, 0},
	/* PLUS */ {ERRST, &errFunc, 0},
	/* MINUS */ {ERRST, &errFunc, 0},
	/* STAR */ {ERRST, &errFunc, 0},
	/* SLASH */ {ERRST, &errFunc, 0},
	/* MOD */ {ERRST, &errFunc, 0},
	/* ! */ {ERRST, &errFunc, 0},
	/* & */ {ERRST, &errFunc, 0},
	/* | */ {ERRST, &errFunc, 0},
	/* < */ {ERRST, &errFunc, 0},
	/* > */ {ERRST, &errFunc, 0},
	/* = */ {TOKST, &returnTok, NOTEQ},
	/* ~ */ {ERRST, &errFunc, 0},
	/* ( */ {TOKST, &returnTok, NOTTOK},
	/* ) */ {ERRST, &errFunc, 0},
	/* [ */ {ERRST, &errFunc, 0},
	/* ] */ {ERRST, &errFunc, 0},
	/* { */ {ERRST, &errFunc, 0},
	/* } */ {ERRST, &errFunc, 0},
	/* , */ {ERRST, &errFunc, 0},
	/* . */ {ERRST, &errFunc, 0},
	/* ? */ {ERRST, &errFunc, 0},
	/* : */ {ERRST, &errFunc, 0},
	/* ; */ {ERRST, &errFunc, 0},
	/* ^ */ {ERRST, &errFunc, 0},
	/* _ */ {TOKST, &returnTok, NOTTOK},
	/* \ */ {ERRST, &errFunc, 0},
	/* # */ {ERRST, &errFunc, 0}
}

,{ /* State row 18 - ANDST (First & found)*/
	/* JUNK */ {ERRST, &errFunc, 0},
	/* WHITESPACE */ {TOKST, &returnTok, ANDTOK},
	/* NUMBERS */ {TOKST, &returnTok, ANDTOK},
	/* CHARS */ {TOKST, &returnTok, ANDTOK},
	/* NEWLINE */ {TOKST, &returnTok, ANDTOK},
	/* ' */ {ERRST, &errFunc, 0},
	/* " */ {ERRST, &errFunc, 0},
	/* PLUS */ {ERRST, &errFunc, 0},
	/* MINUS */ {ERRST, &errFunc, 0},
	/* STAR */ {ERRST, &errFunc, 0},
	/* SLASH */ {ERRST, &errFunc, 0},
	/* MOD */ {ERRST, &errFunc, 0},
	/* ! */ {ERRST, &errFunc, 0},
	/* & */ {TOKST, &errFunc, ANDAND},
	/* | */ {ERRST, &errFunc, 0},
	/* < */ {ERRST, &errFunc, 0},
	/* > */ {ERRST, &errFunc, 0},
	/* = */ {TOKST, &returnTok, ANDEQ},
	/* ~ */ {ERRST, &errFunc, 0},
	/* ( */ {TOKST, &returnTok, ANDTOK},
	/* ) */ {ERRST, &errFunc, 0},
	/* [ */ {ERRST, &errFunc, 0},
	/* ] */ {ERRST, &errFunc, 0},
	/* { */ {ERRST, &errFunc, 0},
	/* } */ {ERRST, &errFunc, 0},
	/* , */ {ERRST, &errFunc, 0},
	/* . */ {ERRST, &errFunc, 0},
	/* ? */ {ERRST, &errFunc, 0},
	/* : */ {ERRST, &errFunc, 0},
	/* ; */ {ERRST, &errFunc, 0},
	/* ^ */ {ERRST, &errFunc, 0},
	/* _ */ {TOKST, &returnTok, ANDTOK},
	/* \ */ {ERRST, &errFunc, 0},
	/* # */ {ERRST, &errFunc, 0}
}

,{ /* State row 19 - ORST (First | found)*/
	/* JUNK */ {ERRST, &errFunc, 0},
	/* WHITESPACE */ {TOKST, &returnTok, ORTOK},
	/* NUMBERS */ {TOKST, &returnTok, ORTOK},
	/* CHARS */ {TOKST, &returnTok, ORTOK},
	/* NEWLINE */ {TOKST, &returnTok, ORTOK},
	/* ' */ {ERRST, &errFunc, 0},
	/* " */ {ERRST, &errFunc, 0},
	/* PLUS */ {ERRST, &errFunc, 0},
	/* MINUS */ {ERRST, &errFunc, 0},
	/* STAR */ {ERRST, &errFunc, 0},
	/* SLASH */ {ERRST, &errFunc, 0},
	/* MOD */ {ERRST, &errFunc, 0},
	/* ! */ {ERRST, &errFunc, 0},
	/* & */ {ERRST, &errFunc, 0},
	/* | */ {TOKST, &returnTok, OROR},
	/* < */ {ERRST, &errFunc, 0},
	/* > */ {ERRST, &errFunc, 0},
	/* = */ {TOKST, &returnTok, OREQ},
	/* ~ */ {ERRST, &errFunc, 0},
	/* ( */ {TOKST, &returnTok, ORTOK},
	/* ) */ {ERRST, &errFunc, 0},
	/* [ */ {ERRST, &errFunc, 0},
	/* ] */ {ERRST, &errFunc, 0},
	/* { */ {ERRST, &errFunc, 0},
	/* } */ {ERRST, &errFunc, 0},
	/* , */ {ERRST, &errFunc, 0},
	/* . */ {ERRST, &errFunc, 0},
	/* ? */ {ERRST, &errFunc, 0},
	/* : */ {ERRST, &errFunc, 0},
	/* ; */ {ERRST, &errFunc, 0},
	/* ^ */ {ERRST, &errFunc, 0},
	/* _ */ {TOKST, &returnTok, ORTOK},
	/* \ */ {ERRST, &errFunc, 0},
	/* # */ {ERRST, &errFunc, 0}
}

,{ /* State row 20 - LTST (First < found)*/
	/* JUNK */ {ERRST, &errFunc, 0},
	/* WHITESPACE */ {TOKST, &returnTok, LTTOK},
	/* NUMBERS */ {TOKST, &returnTok, LTTOK},
	/* CHARS */ {TOKST, &returnTok, LTTOK},
	/* NEWLINE */ {TOKST, &returnTok, LTTOK},
	/* ' */ {TOKST, &returnTok, LTTOK},
	/* " */ {TOKST, &returnTok, LTTOK},
	/* PLUS */ {ERRST, &errFunc, 0},
	/* MINUS */ {ERRST, &errFunc, 0},
	/* STAR */ {ERRST, &errFunc, 0},
	/* SLASH */ {ERRST, &errFunc, 0},
	/* MOD */ {ERRST, &errFunc, 0},
	/* ! */ {ERRST, &errFunc, 0},
	/* & */ {ERRST, &errFunc, 0},
	/* | */ {ERRST, &errFunc, 0},
	/* < */ {TOKST, &returnTok, LSHIFT},
	/* > */ {ERRST, &errFunc, 0},
	/* = */ {TOKST, &returnTok, LTEQ},
	/* ~ */ {ERRST, &errFunc, 0},
	/* ( */ {TOKST, &returnTok, LTTOK},
	/* ) */ {ERRST, &errFunc, 0},
	/* [ */ {ERRST, &errFunc, 0},
	/* ] */ {ERRST, &errFunc, 0},
	/* { */ {ERRST, &errFunc, 0},
	/* } */ {ERRST, &errFunc, 0},
	/* , */ {ERRST, &errFunc, 0},
	/* . */ {ERRST, &errFunc, 0},
	/* ? */ {ERRST, &errFunc, 0},
	/* : */ {ERRST, &errFunc, 0},
	/* ; */ {ERRST, &errFunc, 0},
	/* ^ */ {ERRST, &errFunc, 0},
	/* _ */ {TOKST, &returnTok, LTTOK},
	/* \ */ {ERRST, &errFunc, 0},
	/* # */ {ERRST, &errFunc, 0}
}

,{ /* State row 21 - GTST (First > found)*/
	/* JUNK */ {ERRST, &errFunc, 0},
	/* WHITESPACE */ {TOKST, &returnTok, GTTOK},
	/* NUMBERS */ {TOKST, &returnTok, GTTOK},
	/* CHARS */ {TOKST, &returnTok, GTTOK},
	/* NEWLINE */ {TOKST, &returnTok, GTTOK},
	/* ' */ {TOKST, &returnTok, GTTOK},
	/* " */ {TOKST, &returnTok, GTTOK},
	/* PLUS */ {ERRST, &errFunc, 0},
	/* MINUS */ {ERRST, &errFunc, 0},
	/* STAR */ {ERRST, &errFunc, 0},
	/* SLASH */ {ERRST, &errFunc, 0},
	/* MOD */ {ERRST, &errFunc, 0},
	/* ! */ {ERRST, &errFunc, 0},
	/* & */ {ERRST, &errFunc, 0},
	/* | */ {ERRST, &errFunc, 0},
	/* < */ {ERRST, &errFunc, 0},
	/* > */ {TOKST, &returnTok, RSHIFT},
	/* = */ {TOKST, &returnTok, GTEQ},
	/* ~ */ {ERRST, &errFunc, 0},
	/* ( */ {TOKST, &returnTok, GTTOK},
	/* ) */ {ERRST, &errFunc, 0},
	/* [ */ {ERRST, &errFunc, 0},
	/* ] */ {ERRST, &errFunc, 0},
	/* { */ {ERRST, &errFunc, 0},
	/* } */ {ERRST, &errFunc, 0},
	/* , */ {ERRST, &errFunc, 0},
	/* . */ {ERRST, &errFunc, 0},
	/* ? */ {ERRST, &errFunc, 0},
	/* : */ {ERRST, &errFunc, 0},
	/* ; */ {ERRST, &errFunc, 0},
	/* ^ */ {ERRST, &errFunc, 0},
	/* _ */ {TOKST, &returnTok, GTTOK},
	/* \ */ {ERRST, &errFunc, 0},
	/* # */ {ERRST, &errFunc, 0}
}

,{ /* State row 22 - EQST (First = found)*/
	/* JUNK */ {ERRST, &errFunc, 0},
	/* WHITESPACE */ {TOKST, &returnTok, EQTOK},
	/* NUMBERS */ {TOKST, &returnTok, EQTOK},
	/* CHARS */ {TOKST, &returnTok, EQTOK},
	/* NEWLINE */ {TOKST, &returnTok, EQTOK},
	/* ' */ {TOKST, &returnTok, EQTOK},
	/* " */ {TOKST, &returnTok, EQTOK},
	/* PLUS */ {TOKST, &returnTok, EQTOK},
	/* MINUS */ {TOKST, &returnTok, EQTOK},
	/* STAR */ {ERRST, &errFunc, 0},
	/* SLASH */ {ERRST, &errFunc, 0},
	/* MOD */ {ERRST, &errFunc, 0},
	/* ! */ {ERRST, &errFunc, 0},
	/* & */ {ERRST, &errFunc, 0},
	/* | */ {ERRST, &errFunc, 0},
	/* < */ {ERRST, &errFunc, 0},
	/* > */ {ERRST, &errFunc, 0},
	/* = */ {TOKST, &returnTok, COMPARE},
	/* ~ */ {ERRST, &errFunc, 0},
	/* ( */ {TOKST, &returnTok, EQTOK},
	/* ) */ {ERRST, &errFunc, 0},
	/* [ */ {ERRST, &errFunc, 0},
	/* ] */ {ERRST, &errFunc, 0},
	/* { */ {ERRST, &errFunc, 0},
	/* } */ {ERRST, &errFunc, 0},
	/* , */ {ERRST, &errFunc, 0},
	/* . */ {ERRST, &errFunc, 0},
	/* ? */ {ERRST, &errFunc, 0},
	/* : */ {ERRST, &errFunc, 0},
	/* ; */ {ERRST, &errFunc, 0},
	/* ^ */ {ERRST, &errFunc, 0},
	/* _ */ {TOKST, &returnTok, EQTOK},
	/* \ */ {ERRST, &errFunc, 0},
	/* # */ {ERRST, &errFunc, 0}
}

,{ /* State row 23 - CARETST (First ^ found)*/
	/* JUNK */ {ERRST, &errFunc, 0},
	/* WHITESPACE */ {TOKST, &returnTok, XORTOK},
	/* NUMBERS */ {TOKST, &returnTok, XORTOK},
	/* CHARS */ {TOKST, &returnTok, XORTOK},
	/* NEWLINE */ {TOKST, &returnTok, XORTOK},
	/* ' */ {ERRST, &errFunc, 0},
	/* " */ {ERRST, &errFunc, 0},
	/* PLUS */ {TOKST, &returnTok, XORTOK},
	/* MINUS */ {TOKST, &returnTok, XORTOK},
	/* STAR */ {ERRST, &errFunc, 0},
	/* SLASH */ {ERRST, &errFunc, 0},
	/* MOD */ {ERRST, &errFunc, 0},
	/* ! */ {ERRST, &errFunc, 0},
	/* & */ {ERRST, &errFunc, 0},
	/* | */ {ERRST, &errFunc, 0},
	/* < */ {ERRST, &errFunc, 0},
	/* > */ {ERRST, &errFunc, 0},
	/* = */ {TOKST, &returnTok, XOREQ},
	/* ~ */ {ERRST, &errFunc, 0},
	/* ( */ {TOKST, &returnTok, XORTOK},
	/* ) */ {ERRST, &errFunc, 0},
	/* [ */ {ERRST, &errFunc, 0},
	/* ] */ {ERRST, &errFunc, 0},
	/* { */ {ERRST, &errFunc, 0},
	/* } */ {ERRST, &errFunc, 0},
	/* , */ {ERRST, &errFunc, 0},
	/* . */ {ERRST, &errFunc, 0},
	/* ? */ {ERRST, &errFunc, 0},
	/* : */ {ERRST, &errFunc, 0},
	/* ; */ {ERRST, &errFunc, 0},
	/* ^ */ {ERRST, &errFunc, 0},
	/* _ */ {TOKST, &returnTok, XORTOK},
	/* \ */ {ERRST, &errFunc, 0},
	/* # */ {ERRST, &errFunc, 0}
}

,{ /* State row 24 - HEXST */
	/* JUNK */ {ERRST, &errFunc, 0},
	/* WHITESPACE */ {HEXACCST, &returnTok, HEXTOK},
	/* NUMBERS */ {HEXST, &errFunc, 0},
	/* CHARS */ {HEXST, &errFunc, 0},
	/* NEWLINE */ {HEXACCST, &returnTok, HEXTOK},
	/* ' */ {ERRST, &errFunc, 0},
	/* " */ {ERRST, &errFunc, 0},
	/* PLUS */ {HEXACCST, &returnTok, HEXTOK},
	/* MINUS */ {HEXACCST, &returnTok, HEXTOK},
	/* STAR */ {HEXACCST, &returnTok, HEXTOK},
	/* SLASH */ {HEXACCST, &returnTok, HEXTOK},
	/* MOD */ {HEXACCST, &returnTok, HEXTOK},
	/* ! */ {HEXACCST, &returnTok, HEXTOK},
	/* & */ {HEXACCST, &returnTok, HEXTOK},
	/* | */ {HEXACCST, &returnTok, HEXTOK},
	/* < */ {HEXACCST, &returnTok, HEXTOK},
	/* > */ {HEXACCST, &returnTok, HEXTOK},
	/* = */ {HEXACCST, &returnTok, HEXTOK},
	/* ~ */ {ERRST, &errFunc, 0},
	/* ( */ {ERRST, &errFunc, 0},
	/* ) */ {HEXACCST, &returnTok, HEXTOK},
	/* [ */ {ERRST, &errFunc, 0},
	/* ] */ {HEXACCST, &returnTok, HEXTOK},
	/* { */ {ERRST, &errFunc, 0},
	/* } */ {HEXACCST, &returnTok, HEXTOK},
	/* , */ {HEXACCST, &returnTok, HEXTOK},
	/* . */ {FLOATST, &accumulate, 0},
	/* ? */ {HEXACCST, &returnTok, HEXTOK},
	/* : */ {ERRST, &errFunc, 0},
	/* ; */ {HEXACCST, &returnTok, HEXTOK},
	/* ^ */ {HEXACCST, &returnTok, HEXTOK},
	/* _ */ {ERRST, &errFunc, 0},
	/* \ */ {ERRST, &errFunc, 0},
	/* # */ {ERRST, &errFunc, 0}
}

,{ /* State row 25 - UNUSED */
	/* JUNK */ {ERRST, &errFunc, 0},
	/* WHITESPACE */ {ERRST, &errFunc, 0},
	/* NUMBERS */ {ERRST, &errFunc, 0},
	/* CHARS */ {HEXST, &accumulate, 0},
	/* NEWLINE */ {ERRST, &errFunc, 0},
	/* ' */ {ERRST, &errFunc, 0},
	/* " */ {ERRST, &errFunc, 0},
	/* PLUS */ {ERRST, &errFunc, 0},
	/* MINUS */ {ERRST, &errFunc, 0},
	/* STAR */ {ERRST, &errFunc, 0},
	/* SLASH */ {ERRST, &errFunc, 0},
	/* MOD */ {ERRST, &errFunc, 0},
	/* ! */ {ERRST, &errFunc, 0},
	/* & */ {ERRST, &errFunc, 0},
	/* | */ {ERRST, &errFunc, 0},
	/* < */ {ERRST, &errFunc, 0},
	/* > */ {ERRST, &errFunc, 0},
	/* = */ {ERRST, &errFunc, 0},
	/* ~ */ {ERRST, &errFunc, 0},
	/* ( */ {ERRST, &errFunc, 0},
	/* ) */ {ERRST, &errFunc, 0},
	/* [ */ {ERRST, &errFunc, 0},
	/* ] */ {ERRST, &errFunc, 0},
	/* { */ {ERRST, &errFunc, 0},
	/* } */ {ERRST, &errFunc, 0},
	/* , */ {ERRST, &errFunc, 0},
	/* . */ {ERRST, &errFunc, 0},
	/* ? */ {ERRST, &errFunc, 0},
	/* : */ {ERRST, &errFunc, 0},
	/* ; */ {ERRST, &errFunc, 0},
	/* ^ */ {ERRST, &errFunc, 0},
	/* _ */ {ERRST, &errFunc, 0},
	/* \ */ {ERRST, &errFunc, 0},
	/* # */ {ERRST, &errFunc, 0}
}

};
